name: Python CI (Windows)

on:
  push:
    branches: [ main, setup-task ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  #   windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Show Python version
        run: python --version
      - name: Verify Windows environment
        run: |
          echo "Running on Windows"
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"